public class Class24C3 {
Integer x=10;
 Integer y=20;
 Integer z;
    Public Void addNum()
    {
        System.debug('Value of x='+x);
        System.debug('Value of y='+y);
        System.debug('Value of z='+z);
        z=x+y;
        System.debug('Value of z after add='+z);
    }
    Public Void addNum1(Integer x,Integer y)
    {
        System.debug('Value of x='+x);
        System.debug('Value of y='+y);
        System.debug('Value of z='+z);
        z=x+y;
        System.debug('Value of z after add='+z);
    }
}