public class Day30C3 {
    Public Integer a{get;}
    Public Integer b{set;}
    Public Integer c{get;set;}
    Public Integer d{get{
                       return 100;
                                }
                     set{
                           d=200;
                     }}
    public Integer getA()
    {
        return a;
    }
    Public Integer getset(integer c){
        this.c=c;
        return c;
    }
    
}